### PR TITLE
Fixed bug with loudness not being centered

### PR DESCRIPTION
**Pull request by chrisdonahue**

### CODE REVIEW

**Comment by chrisdonahue** [comment]
Whoops sorry this was supposed to be a PR into my fork. Ignore for now (though this is a bug that might be of interest :)

**Comment by jesseengel** [comment]
For sure if you want to add functionality to allow for centering it'd
always be welcome. We just want to default to non-centered because that's
what we've been working with.

**Comment by chrisdonahue** [comment]
Yeah that's the plan for this once I finish it. For now it's just a quick patch for my own use.

Is there a particular reason y'all prefer non-centered? We've been running into issues because F0 from CREPE is centered but loudness is not (and with a window size of 2048 this results in a sizeable delay).

Here's an example waveform (blue) overlaid with loudness from current `master` branch (orange) and this patch with centering enabled (green): https://i.imgur.com/pK0Lz5B.png

**Comment by jesseengel** [comment]
fwiw, I believe everything (including crepe) is consistently not centered in the codebase currently: https://github.com/magenta/ddsp/blob/master/ddsp/spectral_ops.py#L281

I think I preferred non-centered originally because it was easier for me to reason about on the synthesis side, for designing synthesis windowing that matches the input windowing. Also, it's the default for `tf.signal.stft` and `tf.signal.frame` which we rely on heavily, so it simplified a lot to think of it that way.

practically, It also prevents clicks on the start of synthesis, with a ramp instead. and is causal, so you can just synth a control signal without worrying about the offset.

**Comment by jesseengel** [comment]
Although that plot you have is very compelling, so who knows, maybe we should switch it, or allow the option. Just requires retraining our models. 

Please do let me know if you see evidence it works better.

**Pull request closed without merging**
