### PR TITLE
Make tutorial 0 compatible with Google Colab

### PR DESCRIPTION
**Pull request by egrinstein**
I tried to run tutorial 0 on Google Colab,
but there were some missing imports and casts.

This PR:
* adds the necessary imports and casts
* Creates a sound player using IPython.display
* Shows spectograms using Librosa.display

This is my first PR on Github, I hope you like it.

### CODE REVIEW

**Comment by jesseengel** [comment]
Thanks for the PR! Can you be more specific about what problem you're trying to fix? I just ran 0_processor.ipynb at head on google colab and all the cells run fine (with audio rendering and spectrograms provided by colab_utils.py).

**Comment by egrinstein** [comment]
Hey,

I hadn't seen the colab_utils.py file. So, before running the notebooks you're supposed to paste the colab_utils.py file in a cell? If so, maybe a line in the readme.md file would do...

**Comment by jesseengel** [comment]
Nope, if you just run the cells in order it should do all the imports for you. 

For instance, the first cell, titled `Install and import dependencies` contains all this code:

```
%tensorflow_version 2.x
!pip install -qU ddsp

# Ignore a bunch of deprecation warnings
import warnings
warnings.filterwarnings("ignore")

import ddsp
import ddsp.training
from ddsp.colab.colab_utils import play, specplot, DEFAULT_SAMPLE_RATE
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

sample_rate = DEFAULT_SAMPLE_RATE  # 16000
```

**Comment by egrinstein** [comment]
Oh, I see what happened now.
The install cell was kinda hidden in colab because its title was made using Jupyter magic instead of a markdown cell:

image

Sorry for the inconvenience, I'm gonna close this now.

**Pull request closed without merging**
